default['php-fpm']['php_path'] = '/root/.phpenv/versions/5.5.3/'
default['php-fpm']['php_fpm_conf_path'] = '/root/.phpenv/versions/5.5.3/etc/php-fpm.conf'
default['php-fpm']['php_fpm_bin_path'] = '/root/.phpenv/versions/5.5.3/sbin/php-fpm'
default['php-fpm']['listen'] = '127.0.0.1:9000'
default['php-fpm']['user'] = 'nginx'
default['php-fpm']['group'] = 'nginx'
